In [1]:
import numpy as np
import pandas as pd

# 1. Create a 3x3x3 array with random values 

In [4]:
a=np.random.random(((3,3,3)))
a

array([[[0.52823542, 0.54783126, 0.77108931],
        [0.77251446, 0.41871178, 0.45242046],
        [0.60990711, 0.16180862, 0.66594474]],

       [[0.69465062, 0.27676361, 0.57385748],
        [0.15120584, 0.96224357, 0.69636478],
        [0.67234222, 0.07178103, 0.87971046]],

       [[0.59565704, 0.48253932, 0.72838286],
        [0.27157275, 0.89133177, 0.39751664],
        [0.90772347, 0.70464134, 0.80723952]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
d = np.diag(1+np.arange(4), k = -1)
print (d)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
c = np.ones((3,3))
print("Checkerboard pattern:")
c = np.zeros((8,8),dtype=int)
c[1::2,::2] = 1
c[::2,1::2] = 1
print(c)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [14]:
n=np.random.random((5,5))
print(" oringinal matrix :", n)
nmax=n.max()
nmin=n.min()
n=(n-nmax)/(nmax-nmin)
print(" normalized matrix :", n)

 oringinal matrix : [[0.12193172 0.19363375 0.3748814  0.27741114 0.31177955]
 [0.27074849 0.61834674 0.70755437 0.59499672 0.66544226]
 [0.79542574 0.77254036 0.19158885 0.93948952 0.07817582]
 [0.03318133 0.2082892  0.33049775 0.95464201 0.21813   ]
 [0.64853495 0.8198874  0.15275892 0.16072254 0.08614033]]
 normalized matrix : [[-0.9036851  -0.82587165 -0.62917563 -0.73495362 -0.69765587]
 [-0.74218416 -0.3649589  -0.26814778 -0.39029911 -0.31384925]
 [-0.17278683 -0.19762281 -0.82809085 -0.01644398 -0.95117047]
 [-1.         -0.80996707 -0.67734226  0.         -0.7992875 ]
 [-0.33219763 -0.14624021 -0.87023039 -0.861588   -0.94252712]]


# 5.  How to find common values between two arrays?

In [16]:
ar1 = np.array([2, 5, 8, 9, 7])
print("Array1: ",ar1)
ar2 = [8, 34, 2]
print("Array2: ",ar2)
print("Common values between two arrays:")
print(np.intersect1d(ar1, ar2))

Array1:  [2 5 8 9 7]
Array2:  [8, 34, 2]
Common values between two arrays:
[2 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [17]:
yd = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yd)
td     = np.datetime64('today', 'D')
print("Today: ",td)
tm  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tm)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [20]:
a = np.random.randint(1,2,3)
print("First array:")
print(a)
b = np.random.randint(1,2,3)
print("Second array:")
print(b)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(a, b)
print(array_equal)

First array:
[1 1 1]
Second array:
[1 1 1]
Test above two arrays are equal or not!
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [21]:
a = np.random.random(10)
print("Original array:")
print(a)
a[a.argmax()] = 0
print("Maximum value replaced by 0:")
print(a)

Original array:
[0.34819084 0.8422044  0.44677003 0.52639147 0.4251331  0.57400538
 0.44193093 0.93348636 0.14846948 0.78289925]
Maximum value replaced by 0:
[0.34819084 0.8422044  0.44677003 0.52639147 0.4251331  0.57400538
 0.44193093 0.         0.14846948 0.78289925]


# 9. How to print all the values of an array?

In [34]:
import sys
np.set_printoptions(threshold=sys.maxsize)
x = np.random.random((15, 15))
print(x)

[[9.47509320e-01 5.83817955e-01 6.67998634e-01 4.98372940e-01
  7.15212474e-01 9.63773956e-01 1.56781563e-01 6.62326601e-01
  8.70099905e-01 9.09939654e-01 2.97196651e-01 7.58133893e-01
  6.21499530e-01 6.87366502e-01 3.74741758e-01]
 [4.93231016e-01 3.80453569e-01 6.83233122e-01 6.38713814e-01
  7.83222681e-02 3.60700187e-01 6.80515083e-01 3.34454257e-01
  8.54090730e-01 3.67629891e-01 9.03024231e-01 4.02478160e-01
  8.59226040e-01 1.59973801e-01 8.85906276e-01]
 [5.09623883e-02 7.82722233e-01 2.78557054e-01 6.54912413e-01
  5.20859224e-01 4.70471433e-01 4.79114565e-02 3.96655762e-01
  3.68126480e-01 4.26528301e-01 4.28758602e-01 7.95475010e-01
  5.99577810e-01 3.69848702e-01 4.02866170e-02]
 [5.74509861e-01 8.20713338e-01 3.34103329e-01 5.06352463e-01
  8.34607768e-01 6.61886494e-01 2.64458877e-01 8.22531268e-01
  7.93410516e-01 8.08356747e-01 3.64220464e-01 5.41242493e-02
  1.14930257e-01 1.43412681e-03 4.12996776e-02]
 [8.02414752e-01 7.40240980e-01 5.47590527e-01 4.27737648e-02
  

# 10.Subtract the mean of each row of a matrix

In [38]:

X = np.random.random((5, 10))
print("Original matrix:\n",X)
print()
Y = X - X.mean(axis=1, keepdims=True)
print("\n After subtracting mean of each row of the said matrix:\n",Y)

Original matrix:
 [[0.08723969 0.02440269 0.74944474 0.72902963 0.92501284 0.38882166
  0.38744423 0.99632504 0.03458424 0.57611163]
 [0.80882871 0.09943902 0.01046591 0.1418621  0.31720297 0.12224733
  0.02087855 0.67854171 0.27104215 0.25914816]
 [0.55029809 0.53063175 0.38034026 0.80383573 0.30603586 0.19228631
  0.16427689 0.54252537 0.36425665 0.30025315]
 [0.32076255 0.9517168  0.11984716 0.61905523 0.75730358 0.6875832
  0.80379545 0.57760252 0.33658959 0.73935977]
 [0.32304793 0.14404747 0.64750669 0.39342323 0.39668629 0.19923374
  0.13203176 0.96936634 0.90069921 0.22196878]]


 After subtracting mean of each row of the said matrix:
 [[-0.40260195 -0.46543895  0.2596031   0.23918799  0.4351712  -0.10101998
  -0.10239741  0.50648341 -0.4552574   0.08626999]
 [ 0.53586305 -0.17352664 -0.26249975 -0.13110356  0.04423731 -0.15071833
  -0.25208711  0.40557605 -0.00192352 -0.0138175 ]
 [ 0.13682408  0.11715774 -0.03313374  0.39036173 -0.10743815 -0.22118769
  -0.24919712  0.1290513

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(Z)
print(I)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4 2 3 4 8 1 3 2 8 2 2 9 7 4 1 5 3 8 5 3]


In [13]:
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 3. 5. 5. 4. 3. 1. 2. 4. 2.]


# 12.How to get the diagonal of a dot product?

In [9]:
x=np.random.random((3,5))
y=x=np.random.random((5,5))
z = np.diag(x.dot(y))
z = (x * y.T).sum(-1)
print("x : ",x)
print("y : ",y)
print("z : ",z)

x :  [[0.55201995 0.97939464 0.26683964 0.72218051 0.11603013]
 [0.61274993 0.843444   0.39495535 0.92805033 0.37753774]
 [0.52255657 0.63812617 0.15533463 0.98748814 0.72709975]
 [0.69795669 0.02119178 0.21639148 0.11287868 0.12853238]
 [0.31908764 0.69491596 0.71555437 0.02220501 0.48631195]]
y :  [[0.55201995 0.97939464 0.26683964 0.72218051 0.11603013]
 [0.61274993 0.843444   0.39495535 0.92805033 0.37753774]
 [0.52255657 0.63812617 0.15533463 0.98748814 0.72709975]
 [0.69795669 0.02119178 0.21639148 0.11287868 0.12853238]
 [0.31908764 0.69491596 0.71555437 0.02220501 0.48631195]]
z :  [1.58536333 1.84557717 1.14956243 0.75299744 1.05901356]


# 13.How to find the most frequent value in an array?

In [7]:
import numpy as np
x = np.random.randint(0, 10, 20)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[7 8 8 0 3 0 2 9 4 9 2 4 7 0 0 3 6 8 4 7]
Most frequent value in the above array:
0


# 14.How to get the n largest values of an array

In [5]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 3
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[7 8 9]


# 15.How to create a record array from a regular array?

In [1]:
import numpy as np
regarray = np.array([("India", 7, 2),
                 ("Canada", 5, 15),
             ("Germany", 24, 18)])
print("Regular arrays:")
print(regarray)


Regular arrays:
[['India' '7' '2']
 ['Canada' '5' '15']
 ['Germany' '24' '18']]


In [3]:
print("\nRecord array;")
record = np.core.records.fromarrays(regarray.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(record)


Record array;
[(b'India',  7.,  2) (b'Canada',  5., 15) (b'Germany', 24., 18)]
